name: Python Package

on:
  push:
    branches:
      - main
  release:
    branches:
      - main

jobs:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
          - macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build CKZG
        working-directory: src
        run: make

      - uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5

      - name: Build wheels
        working-directory: bindings/python
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        working-directory: bindings/python
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
          packages-dir: wheelhouse
